site_name: RIT k8s RDMA Documentation

nav:
    - Home: index.md
    - Introduction: introduction.md
    - Components: components.md
    - Install: install.md
    - Helpful Commands and Tools: helpAndTools.md
    - Glossary: glossary.md
theme: readthedocs